---
title: "Day-6 Regression Analysis"
categories:
- R
output:
  html_document:
    toc : true
    toc_float : true
    keep_md: true
date: '2022-06-24'
---




# Statistics

## 추론통계(Inferential Statistics)

### 통계검정

- 평균 차이 검정 : 수치 데이터 + 범주 데이터(두그룹)
  - 양끝 차이 검정 
- 비율 차이 검정 : 범주 데이터
- 상관 관계 : 수치 데이터
- 회귀

- 통계 검정 사전 준비
  - 분석을 위한 데이터가 적절한지 검정
    - 등분산 검정, 수치 데이터가 정규분포를 이루는가(정균성 검정)

- 귀무가설, 대립가설 설정
  - 귀무가설 : 평균 차이가 없다, p > 0.05
  - 대립가설 : 평균 차이가 있다, p < 0.05

- 테스트
  - t.test, chisq.test, cor.test
    
### 회귀(별이 5개!)
- 기초 통계 : 특정한 결과에 영향을 주는 요인을 찾는 것
- 귀무가설 & 대립가설
  - 귀무가설 : x(독립변수)가 y(종속변수)에 영향을 주지 않는다.
  - 대립가설 : x(독립변수)가 y(종속변수)에 영향을 준다

```r
RA <- lm(data=mtcars, mpg~disp)
summary(RA)
```

```
## 
## Call:
## lm(formula = mpg ~ disp, data = mtcars)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.8922 -2.2022 -0.9631  1.6272  7.2305 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept) 29.599855   1.229720  24.070  < 2e-16 ***
## disp        -0.041215   0.004712  -8.747 9.38e-10 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 3.251 on 30 degrees of freedom
## Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709 
## F-statistic: 76.51 on 1 and 30 DF,  p-value: 9.38e-10
```

- lm(종속변수 ~ 독립변수, data)
  - p.value > 0.05 : 식이 의미가 없다. -> 의미있게 데이터를 가공 -> 데이터삭제 or 데이터수집
  - 요인의 Intercept(기울기) > 0.05 -> 요인삭제 후 재실행
  - 컬럼의 t값이 0.05가 넘으면 그 컬럼을 지워본후 실행하고 p값과 t값을 다시 확인한다. -> 반복
    - 전진선택법
      - 절편만 있는 상수모형으로부터 시작해 중요하다고 생각되는 설명변수부터 차례로 모형에 추가
      - 장점 : 이해하기 쉽고 변수의 개수가 많은 경우에도 사용 가능
      - 단점 : 작은 변동에도 결과가 크게 달라져 안정성 부족
    - 후진제거법
      - 모든 독립변수를 포함한 모형에서 출발해 가장 적은 영향을 주는 변수부터 제거하면서 더 이상 제거할 변수가 없을 때까지 진행
      - 장점 : 전체 변수들의 정보를 이용할수 있다
      - 단점 : 변수의 개수가 많으면 사용하기 어려움

```r
##Multiple R-squared:  0.7183,	Adjusted R-squared:  0.709 
```
  - R-squared(결정계수) = 설명력 <- 0 ~ 1
    - 1로 수렴할수록 설명력이 좋다
    - 결정계수값만큼 결과에 영향을 주는 요인이다.
      - 1 - 결정계수값의 결과 만큼 다른 요인을 더 찾아야한다.

- 머신러닝, 인공지능 : 예측을 하기위해 
  - y = ax + b에서 파생되는 것들이 대부분이다.
  
## 사례 분석
- 문제1 : 삶의 만족도와 외로움이 자살충동에 주는 영향
- 문제2 : 삶의 만족도와 외로움의 상관관계를 알아보기
- 문제3 : 가족신뢰도, 경제적 안정, 건강상태가 삶의 만족도와 외로움에 주는 영향
- 문제4 : 성, 연령, 지역에 따라 삶의 만족도에 차이가 있는가


```r
library(dplyr)
```

```
## 
## 다음의 패키지를 부착합니다: 'dplyr'
```

```
## The following objects are masked from 'package:stats':
## 
##     filter, lag
```

```
## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
```

```r
library(ggplot2)
```


```r
#install.packages("foreign")
library(foreign)
```


```r
mental = read.spss("data/한국행정연구원_사회통합실태조사_데이터_2019.sav")
```

```
## re-encoding from CP51949
```

```r
class(mental)
```

```
## [1] "list"
```

```r
mental = as.data.frame(mental) # 데이터프레임으로 변경
class(mental)
```

```
## [1] "data.frame"
```

### 데이터 가공

```r
mental <- mental %>%
  select(q32_2, q1_4, q32_1, q34_1, q52, d17, d1, d2, ara) %>%
  rename(suicide=q32_2,
         satisfaction=q1_4,
         loneliness=q32_1,
         family_belief=q34_1,
         wealth=q52,
         health=d17,
         sex=d1,
         age=d2,
         area=ara
         ) # 변수 추출 후 변수 이름 변경
str(mental)
```

```
## 'data.frame':	8000 obs. of  9 variables:
##  $ suicide      : Factor w/ 4 levels "전혀 그렇지 않다",..: 2 2 2 1 1 2 3 3 1 2 ...
##  $ satisfaction : Factor w/ 12 levels "0점 전혀 만족하지 않는다",..: 5 5 5 4 7 5 6 6 5 5 ...
##  $ loneliness   : Factor w/ 4 levels "전혀 그렇지 않다",..: 2 2 2 2 1 2 3 3 1 2 ...
##  $ family_belief: Factor w/ 4 levels "전혀 신뢰하지 않는다",..: 3 3 2 2 4 2 2 2 4 3 ...
##  $ wealth       : Factor w/ 11 levels "0점 전혀 안정적이지 않다",..: 4 7 6 6 7 7 6 5 4 6 ...
##  $ health       : Factor w/ 5 levels "매우 나쁘다",..: 4 3 4 4 4 4 4 4 4 4 ...
##  $ sex          : Factor w/ 2 levels "남성","여성": 2 2 1 2 1 2 2 1 2 1 ...
##  $ age          : Factor w/ 5 levels "19~29세","30대",..: 5 5 4 4 3 3 1 5 5 3 ...
##  $ area         : Factor w/ 17 levels "서울","부산",..: 1 1 1 1 1 1 1 1 1 1 ...
```

```r
table(mental$suicide)     # 빈도확인
```

```
## 
## 전혀 그렇지 않다 별로 그렇지 않다      약간 그렇다      매우 그렇다 
##             5592             1862              479               67
```

```r
table(mental$health)      # 빈도확인
```

```
## 
## 매우 나쁘다 나쁜 편이다    보통이다 좋은 편이다   매우 좋다 
##          87         509        2413        3730        1261
```

```r
table(mental$satisfaction)# 빈도확인
```

```
## 
## 0점 전혀 만족하지 않는다                      1점                      2점 
##                       49                       79                      170 
##                      3점                      4점                 5점 보통 
##                      302                      440                     2053 
##                      6점                      7점                      8점 
##                     1611                     1761                     1040 
##                      9점       10점 매우 만족한다              모름/무응답 
##                      321                      174                        0
```

```r
# 문제중 자살충동 = y , 삶의 만족도와 외로움이 변수인데, 삶의 만족도와 외로움에 영향을 주는 변수가 신뢰도, 경제적안정, 건강상태이므로 변수가 6개이다
mental$suicide <-as.integer(mental$suicide)
mental$satisfaction <-as.integer(mental$satisfaction)
mental$loneliness <- as.integer(mental$loneliness)
mental$family_belief <-as.integer(mental$family_belief)
mental$wealth <- as.integer(mental$wealth)
mental$health <- as.integer(mental$health)

table(mental$suicide)
```

```
## 
##    1    2    3    4 
## 5592 1862  479   67
```

```r
table(mental$health)
```

```
## 
##    1    2    3    4    5 
##   87  509 2413 3730 1261
```

```r
table(mental$satisfaction)
```

```
## 
##    1    2    3    4    5    6    7    8    9   10   11 
##   49   79  170  302  440 2053 1611 1761 1040  321  174
```

```r
# 원래는 0점부터 시작하는데 첫 문항을 1로 시작해서 1씩 빼주는 작업
mental$satisfaction <- mental$satisfaction-1 
mental$wealth <- mental$wealth-1
table(mental$satisfaction)
```

```
## 
##    0    1    2    3    4    5    6    7    8    9   10 
##   49   79  170  302  440 2053 1611 1761 1040  321  174
```

```r
# sex, age, area의 유형을 범주형에서 문자열로 변경 -> 범주형으로 분석하면 오류가 발생할수 있기 때문
mental$sex <- as.character(mental$sex)
mental$age <- as.character(mental$age)
mental$area <- as.character(mental$area)
table(mental$sex)
```

```
## 
## 남성 여성 
## 4011 3989
```

```r
table(mental$age)
```

```
## 
## 19~29세    30대    40대    50대 60~69세 
##    1542    1516    1769    1821    1352
```

```r
table(mental$area)
```

```
## 
## 강원 경기 경남 경북 광주 대구 대전 부산 서울 세종 울산 인천 전남 전북 제주 충남 
##  388 1103  527  466  353  464  356  539  965  162  324  522  395  381  267  425 
## 충북 
##  363
```

```r
# age변수에 범주에 20대, 60대가 다른범주와 다른이름으로 나와서 통일시켜준다
mental$age <- ifelse(mental$age=="19~29세", "20대",
                     ifelse(mental$age=="60~69세","60대",mental$age))
summary(mental) # 결측치, 이상치 확인
```

```
##     suicide       satisfaction      loneliness    family_belief  
##  Min.   :1.000   Min.   : 0.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:1.000   1st Qu.: 5.000   1st Qu.:1.000   1st Qu.:3.000  
##  Median :1.000   Median : 6.000   Median :2.000   Median :4.000  
##  Mean   :1.378   Mean   : 6.037   Mean   :1.795   Mean   :3.576  
##  3rd Qu.:2.000   3rd Qu.: 7.000   3rd Qu.:2.000   3rd Qu.:4.000  
##  Max.   :4.000   Max.   :10.000   Max.   :4.000   Max.   :4.000  
##      wealth           health          sex                age           
##  Min.   : 0.000   Min.   :1.000   Length:8000        Length:8000       
##  1st Qu.: 4.000   1st Qu.:3.000   Class :character   Class :character  
##  Median : 5.000   Median :4.000   Mode  :character   Mode  :character  
##  Mean   : 4.985   Mean   :3.696                                        
##  3rd Qu.: 6.000   3rd Qu.:4.000                                        
##  Max.   :10.000   Max.   :5.000                                        
##      area          
##  Length:8000       
##  Class :character  
##  Mode  :character  
##                    
##                    
## 
```

### 데이터 분석
- 연구할 때는 우선 인구사회적 변수의 빈도분석(빈도와 비율확인)

```r
# 성별 빈도분석
mental %>%
  group_by(sex) %>%                 
  summarise(n=n()) %>%              # sex변수의 범주별 빈도
  mutate(total=sum(n),              # sex변수의 빈도총계
         pct=round(n/total*100, 1)) # sex변수의 범주별 비율 
```

```
## # A tibble: 2 × 4
##   sex       n total   pct
##   <chr> <int> <int> <dbl>
## 1 남성   4011  8000  50.1
## 2 여성   3989  8000  49.9
```

```r
# 연령대별 빈도분석
mental %>%
  group_by(age) %>%
  summarise(n=n()) %>%
  mutate(total=sum(n),
         pct=round(n/total*100, 1))
```

```
## # A tibble: 5 × 4
##   age       n total   pct
##   <chr> <int> <int> <dbl>
## 1 20대   1542  8000  19.3
## 2 30대   1516  8000  19  
## 3 40대   1769  8000  22.1
## 4 50대   1821  8000  22.8
## 5 60대   1352  8000  16.9
```

```r
# 성별, 연령대 고르게 분포되어있는 것을 볼 수 있다.

# 교차분석 - 성별로 연령대가 고르게 분포되어 있는가
table(mental$sex, mental$age)
```

```
##       
##        20대 30대 40대 50대 60대
##   남성  822  745  900  891  653
##   여성  720  771  869  930  699
```

```r
# 성과 연령대의 교차 백분율 구하기, 행별로 100%기준, 소수점한자리
round(prop.table(table(mental$sex, mental$age),1)*100,1) 
```

```
##       
##        20대 30대 40대 50대 60대
##   남성 20.5 18.6 22.4 22.2 16.3
##   여성 18.0 19.3 21.8 23.3 17.5
```

```r
chisq.test(mental$sex, mental$age)
```

```
## 
## 	Pearson's Chi-squared test
## 
## data:  mental$sex and mental$age
## X-squared = 10.076, df = 4, p-value = 0.03916
```

```r
# p <0.05  ->  분포의 차이가 있다.

#평균분석(suicide, satisfaction, loneliness, family_belief, wealth, health)
mental %>%
  summarise(m1=mean(suicide), m2=mean(satisfaction), m3=mean(loneliness), 
            m4= mean(family_belief), m5=mean(wealth), m6=mean(health))
```

```
##         m1     m2    m3       m4       m5       m6
## 1 1.377625 6.0365 1.795 3.576375 4.985125 3.696125
```

- 문제1 : 삶의 만족도와 외로움이 자살충동에 미치는 영향
  - 삶의 만족도 와 외로움 = 독립변수
  - 자살충동 = 종속변수

```r
# 다중회귀분석
RA <- lm(data = mental, suicide ~ satisfaction + loneliness)
summary(RA)
```

```
## 
## Call:
## lm(formula = suicide ~ satisfaction + loneliness, data = mental)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.50517 -0.40228 -0.03487  0.17773  3.07029 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)   1.035551   0.029823   34.72   <2e-16 ***
## satisfaction -0.052583   0.003614  -14.55   <2e-16 ***
## loneliness    0.367405   0.007987   46.00   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.5451 on 7997 degrees of freedom
## Multiple R-squared:  0.2668,	Adjusted R-squared:  0.2666 
## F-statistic:  1455 on 2 and 7997 DF,  p-value: < 2.2e-16
```
  - p < 0.001로 적합
  - 회귀식 : 1.035551-0.052583*satisfaction+0.367405*loneliness
  - t < 0.001
  - 설명력 : 0.2668

- 문제2 : 삶의 만족도와 외로움의 상관관계

```r
cor.test(mental$satisfaction, mental$loneliness)
```

```
## 
## 	Pearson's product-moment correlation
## 
## data:  mental$satisfaction and mental$loneliness
## t = -25.374, df = 7998, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.2931116 -0.2525481
## sample estimates:
##        cor 
## -0.2729512
```
  - r=-0.27이므로 삶의 만족도와 외로움은 약한 부정의 관계이다
- 문제3 : 가족신뢰도, 경제안정도, 건강상태가 삶의 만족도와 외로움에 미치는 영향
  - 가족신뢰도, 경제안정도, 건강상태 : 독립변수
  - 삶의 만족도, 외로움 : 종속 변수

```r
RA <- lm(data = mental, satisfaction ~ family_belief+wealth+health)
summary(RA)
```

```
## 
## Call:
## lm(formula = satisfaction ~ family_belief + wealth + health, 
##     data = mental)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.8274 -0.9431 -0.0425  1.0569  6.1986 
## 
## Coefficients:
##               Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    2.07613    0.13765   15.08   <2e-16 ***
## family_belief  0.36851    0.03196   11.53   <2e-16 ***
## wealth         0.26016    0.01089   23.88   <2e-16 ***
## health         0.36403    0.02206   16.50   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 1.627 on 7996 degrees of freedom
## Multiple R-squared:  0.1386,	Adjusted R-squared:  0.1383 
## F-statistic: 428.8 on 3 and 7996 DF,  p-value: < 2.2e-16
```
  - p < 0.001
  - t < 0.001 (유의수준)
  - 회귀식 : 2.07613+0.36851*family_belief+0.26016*wealth+0.36403*health
  - 영향력 : 가족신뢰도 > 경제안정도 > 건강상태
  - 설명력 : 0.1386

```r
RA <- lm(data = mental, loneliness ~ family_belief+wealth+health)
summary(RA)
```

```
## 
## Call:
## lm(formula = loneliness ~ family_belief + wealth + health, data = mental)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.24066 -0.64247  0.01863  0.43022  2.83959 
## 
## Coefficients:
##                Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    3.652247   0.063109   57.87   <2e-16 ***
## family_belief -0.220274   0.014654  -15.03   <2e-16 ***
## wealth        -0.072686   0.004995  -14.55   <2e-16 ***
## health        -0.191313   0.010116  -18.91   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.746 on 7996 degrees of freedom
## Multiple R-squared:  0.1157,	Adjusted R-squared:  0.1154 
## F-statistic: 348.9 on 3 and 7996 DF,  p-value: < 2.2e-16
```
  - p < 0.001
  - t < 0.001
  - 회귀식 : 3.652247-0.220274*family_belief-0.072686*wealth-0.191313*health
  - 영향력 : 가족신뢰도 > 건강상태 > 경제안정도
  - 설명력 : 0.1157
- 문제4 : 성, 연령, 지역별 삶의 만족도차이
  - 성별 삶의 만족도 차이

```r
t.test(data=mental, satisfaction~sex) 
```

```
## 
## 	Welch Two Sample t-test
## 
## data:  satisfaction by sex
## t = -3.7719, df = 7997.6, p-value = 0.0001632
## alternative hypothesis: true difference in means between group 남성 and group 여성 is not equal to 0
## 95 percent confidence interval:
##  -0.22446298 -0.07094075
## sample estimates:
## mean in group 남성 mean in group 여성 
##           5.962852           6.110554
```
    - p < 0.001
    - 남성의 만족도 < 여성의 만족도
  - 연령대별 삶의 만족도 차이

```r
mental %>%
  group_by(age) %>%
  summarise(m=mean(satisfaction)) %>%
  arrange(desc(m))
```

```
## # A tibble: 5 × 2
##   age       m
##   <chr> <dbl>
## 1 30대   6.13
## 2 50대   6.08
## 3 40대   6.05
## 4 20대   6.04
## 5 60대   5.84
```
    - 30대가 제일 높고 60대가 제일 낮다
  - 지역별 삶의 만족도 분석과 그래프 그리기

```r
area_satisfaction <- mental %>%
  group_by(area) %>%
  summarise(m=mean(satisfaction)) %>%
  arrange(desc(m))
str(area_satisfaction)
```

```
## tibble [17 × 2] (S3: tbl_df/tbl/data.frame)
##  $ area: chr [1:17] "제주" "강원" "세종" "충북" ...
##  $ m   : num [1:17] 6.49 6.49 6.4 6.26 6.22 ...
```

```r
ggplot(data=area_satisfaction, aes(x=reorder(area,m),y=m,)) +
  geom_col() +
  labs(
    title = "지역별 만족도",
    x = "지역",
    y = "만족도",
  ) + coord_flip()
```
s
![](/images/day0624/unnamed-chunk-17-1.png)<!-- -->





